name: Java REST Assured API Test CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK 21 environment
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'

      # Cache Maven dependencies to speed up the build process
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Install Maven dependencies without running tests
      - name: Install dependencies
        run: mvn install -DskipTests

      # Run the tests
      - name: Run tests
        run: mvn test

      # Archive test reports for analysis
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: target/surefire-reports/
